import type { QuizQuestion } from "../quizData";

export const positionQuestions: QuizQuestion[] = [
  {
    id: "pos-1",
    difficulty: "club",
    scenario: "6인 테이블에서 딜러 버튼이 당신 앞에 있습니다.",
    question: "당신의 포지션은 무엇입니까?",
    options: ["UTG (언더 더 건)", "CO (컷오프)", "BTN (버튼/딜러)", "SB (스몰 블라인드)"],
    correctIndex: 2,
    explanation: "딜러 버튼이 당신 앞에 있으면 BTN(버튼) 포지션입니다. 포스트플롭에서 마지막으로 행동하기 때문에 다른 플레이어의 액션을 모두 확인한 후 결정할 수 있어 가장 유리한 자리입니다. 실전에서 BTN은 가장 수익적인 포지션이므로 넓은 핸드 레인지로 플레이합니다.",
    hint: "딜러 칩이 놓인 자리가 버튼 포지션입니다.",
  },
  {
    id: "pos-2",
    difficulty: "club",
    scenario: "프리플롭에서 가장 먼저 행동해야 하는 플레이어가 있습니다.",
    question: "이 포지션을 무엇이라 부릅니까?",
    options: ["BTN", "BB (빅 블라인드)", "UTG (언더 더 건)", "SB (스몰 블라인드)"],
    correctIndex: 2,
    explanation: "UTG(Under The Gun)는 빅 블라인드 왼쪽에 앉은 플레이어로, 프리플롭에서 가장 먼저 행동합니다. '총구 아래'라는 뜻처럼 뒤에 많은 플레이어가 남아 있어 압박이 가장 큽니다. 실전에서 UTG는 강한 핸드만 플레이하는 것이 기본 전략입니다.",
    hint: "블라인드 다음 순서, 즉 BB 왼쪽이 첫 번째 행동자입니다.",
  },
  {
    id: "pos-9",
    difficulty: "club",
    scenario: "포커 테이블에서 SB(스몰 블라인드)와 BB(빅 블라인드)는 강제 베팅을 합니다.",
    question: "일반적으로 SB와 BB의 금액 관계는?",
    options: [
      "SB = BB의 절반 (예: 1/2 게임에서 SB=$1, BB=$2)",
      "SB = BB와 동일",
      "SB = BB의 2배",
      "SB는 게임마다 다르고 규칙이 없다"
    ],
    correctIndex: 0,
    explanation: "표준 텍사스 홀덤에서 SB는 BB의 절반입니다. 예를 들어 '1/2' 게임은 SB=$1, BB=$2입니다. 블라인드는 매 핸드 액션을 유도하는 강제 베팅이며, 블라인드 포지션은 프리플롭에서 정보 없이 칩을 넣으므로 장기적으로 손실이 발생하는 자리입니다. 블라인드 방어와 스틸은 이 손실을 줄이기 위한 핵심 전략입니다.",
    hint: "'1/2 게임'에서 앞의 숫자가 SB, 뒤가 BB입니다.",
  },
  {
    id: "pos-3",
    difficulty: "diamond",
    scenario: "포스트플롭(플롭, 턴, 리버)에서 행동 순서가 프리플롭과 다릅니다.",
    question: "포스트플롭에서 가장 먼저 행동하는 포지션은?",
    options: ["UTG", "BTN", "SB (또는 SB 폴드 시 BB)", "CO"],
    correctIndex: 2,
    explanation: "포스트플롭에서는 SB부터 시작하여 시계 방향으로 행동합니다. SB가 폴드했다면 BB부터 시작합니다. BTN이 핸드에 참여 중이라면 마지막에 행동하게 되어 정보 우위를 가집니다. 실전에서 포스트플롭 순서를 정확히 아는 것은 포지셔널 플레이의 기본입니다.",
    hint: "프리플롭: UTG 먼저 / 포스트플롭: SB 먼저",
  },
  {
    id: "pos-5",
    difficulty: "diamond",
    scenario: "6인 테이블의 포지션 순서를 정리하고 있습니다.",
    question: "프리플롭 행동 순서가 올바른 것은?",
    options: [
      "SB → BB → UTG → HJ → CO → BTN",
      "UTG → HJ → CO → BTN → SB → BB",
      "BTN → SB → BB → UTG → HJ → CO",
      "BB → SB → UTG → HJ → CO → BTN"
    ],
    correctIndex: 1,
    explanation: "6인 테이블 프리플롭 행동 순서: UTG → HJ → CO → BTN → SB → BB. 블라인드(SB, BB)는 강제 베팅을 이미 냈으므로 마지막에 행동합니다. BB가 마지막으로 행동하며 체크 또는 레이즈 옵션이 있습니다. 이 순서를 정확히 아는 것이 포지셔널 플레이의 출발점입니다.",
    hint: "프리플롭에서 블라인드는 강제 베팅 후 마지막에 결정합니다.",
  },
  {
    id: "pos-6",
    difficulty: "diamond",
    scenario: "당신은 BTN에 앉아 있습니다. 모든 플레이어가 폴드했고 SB와 BB만 남았습니다.",
    question: "'블라인드 스틸'이란 무엇이며 왜 BTN에서 자주 시도합니까?",
    options: [
      "레이즈하여 블라인드를 폴드시키고 팟을 가져오는 것. BTN이 포스트플롭 포지션 우위가 있기 때문",
      "블라인드 금액만큼만 콜하는 것",
      "올인하여 블라인드를 위협하는 것",
      "SB가 레이즈한 후 리레이즈하는 것"
    ],
    correctIndex: 0,
    explanation: "블라인드 스틸은 BTN(또는 CO)에서 레이즈하여 블라인드를 폴드시키는 전략입니다. BTN은 포스트플롭에서 마지막에 행동하므로, 콜당하더라도 포지션 우위를 가지고 플레이할 수 있습니다. 블라인드 스틸은 장기적으로 수익을 만드는 핵심 전략 중 하나입니다.",
    hint: "BTN은 뒤에 2명(블라인드)만 남아 스틸 성공률이 높습니다.",
    tableInfo: {
      players: [
        { position: "UTG", action: "fold" },
        { position: "HJ", action: "fold" },
        { position: "CO", action: "fold" },
        { position: "BTN", isActive: true, stackSize: "$200" },
        { position: "SB", stackSize: "$100" },
        { position: "BB", stackSize: "$200" },
      ],
      heroPosition: "BTN",
      dealerPosition: "BTN",
      sbAmount: "$1",
      bbAmount: "$2",
    },
  },
  {
    id: "pos-4",
    difficulty: "heart",
    scenario: "당신은 CO(컷오프) 포지션에 앉아 있고 A♠J♥를 받았습니다. 앞선 모든 플레이어가 폴드했습니다.",
    question: "CO에서 AJo로 레이즈하는 것이 일반적으로 좋은 이유는?",
    options: [
      "뒤에 BTN, SB, BB 3명만 남아 폴드될 확률이 높고, 포지셔널 어드밴티지가 있다",
      "AJ는 프리미엄 핸드이므로 어떤 포지션에서든 레이즈해야 한다",
      "CO는 블라인드에 가까워 블라인드 스틸 확률이 높다",
      "AJ는 항상 3-벳해야 하는 핸드이다"
    ],
    correctIndex: 0,
    explanation: "CO에서 앞이 모두 폴드되면 뒤에 3명만 남습니다. AJo는 이 3명의 랜덤 핸드 대비 충분한 에퀴티를 갖습니다. 또한 BTN만 콜하면 포지션을 가지고, 블라인드만 콜하면 포스트플롭에서 포지셔널 어드밴티지가 있습니다.",
    hint: "포지션이 좋을수록 더 넓은 핸드 레인지로 오픈할 수 있습니다.",
    holeCards: [{ rank: "A", suit: "spades" }, { rank: "J", suit: "hearts" }],
    tableInfo: {
      players: [
        { position: "UTG", action: "fold" },
        { position: "HJ", action: "fold" },
        { position: "CO", isActive: true, stackSize: "$200" },
        { position: "BTN", stackSize: "$180" },
        { position: "SB", stackSize: "$150" },
        { position: "BB", stackSize: "$200" },
      ],
      heroPosition: "CO",
      dealerPosition: "BTN",
      sbAmount: "$1",
      bbAmount: "$2",
    },
  },
  {
    id: "pos-8",
    difficulty: "heart",
    scenario: "당신은 IP(인 포지션)에서 플롭 체크백 후 턴에서 상대가 다시 체크합니다.",
    question: "'포지셔널 어드밴티지'가 이 상황에서 왜 중요합니까?",
    options: [
      "상대의 체크를 보고 약한 핸드인지 판단한 뒤 블러프 또는 밸류벳을 선택할 수 있다",
      "체크백하면 항상 무료 카드를 볼 수 있다",
      "IP에서는 항상 베팅해야 한다",
      "포지션은 턴 이후에는 의미가 없다"
    ],
    correctIndex: 0,
    explanation: "IP(인 포지션)에서는 상대의 행동을 먼저 본 후 결정합니다. 상대가 두 번 체크하면 약한 레인지일 가능성이 높고, 블러프 또는 씬 밸류벳으로 팟을 가져올 기회가 됩니다. 이것이 포지셔널 어드밴티지의 핵심입니다.",
    hint: "마지막에 행동하면 상대의 행동에서 정보를 얻을 수 있습니다.",
  },
  {
    id: "pos-10",
    difficulty: "heart",
    scenario: "BTN이 레이즈하고 SB가 콜했습니다. 당신은 BB에서 A♠T♦를 갖고 있습니다.",
    question: "BB에서 이 핸드로 3-벳(리레이즈)하는 것이 합리적인 이유는?",
    options: [
      "BB는 포지션이 불리하므로 3-벳으로 팟을 키우거나 폴드시켜 포지션 불리를 상쇄해야 한다",
      "ATo는 프리미엄 핸드이므로 항상 3-벳한다",
      "BB에서는 절대 3-벳하지 않고 콜만 해야 한다",
      "SB가 콜했으므로 3-벳은 불가능하다"
    ],
    correctIndex: 0,
    explanation: "BB는 포스트플롭에서 OOP(아웃 오브 포지션)으로 불리합니다. 3-벳으로 상대를 폴드시키면 포지션 불리 없이 팟을 가져갈 수 있고, 콜당해도 이니셔티브를 가져가서 포스트플롭 플레이가 수월해집니다.",
    hint: "OOP에서 콜만 하면 포지션 불리가 지속됩니다. 3-벳은 이를 상쇄하는 도구입니다.",
    holeCards: [{ rank: "A", suit: "spades" }, { rank: "T", suit: "diamonds" }],
    tableInfo: {
      players: [
        { position: "UTG", action: "fold" },
        { position: "HJ", action: "fold" },
        { position: "CO", action: "fold" },
        { position: "BTN", action: "raise", betAmount: "$6" },
        { position: "SB", action: "call", betAmount: "$6", stackSize: "$190" },
        { position: "BB", isActive: true, stackSize: "$200" },
      ],
      heroPosition: "BB",
      dealerPosition: "BTN",
      sbAmount: "$1",
      bbAmount: "$2",
    },
  },
  {
    id: "pos-7",
    difficulty: "spade",
    scenario: "9인 풀링 테이블에서 당신은 UTG입니다. K♠Q♠를 받았습니다.",
    question: "UTG에서 KQs를 오픈하는 판단으로 가장 적절한 것은?",
    options: [
      "오픈 가능하지만 뒤에 8명이 남아 강한 핸드와 마주칠 확률이 높으므로 주의가 필요하다",
      "KQs는 어떤 포지션에서든 항상 레이즈해야 하는 프리미엄 핸드이다",
      "UTG에서는 AA, KK, QQ, AK만 오픈해야 한다",
      "KQs는 수티드이므로 UTG에서도 항상 안전하다"
    ],
    correctIndex: 0,
    explanation: "9인 테이블 UTG에서 KQs는 오픈 가능한 핸드지만 경계선상입니다. 뒤에 8명이 남아 있어 프리미엄 핸드(AA, KK, AK 등)와 마주칠 확률이 높습니다. 레이트 포지션에서는 훨씬 편하게 플레이할 수 있는 핸드입니다.",
    hint: "UTG 레인지는 좁아야 합니다 — 뒤에 남은 플레이어가 많을수록 위험합니다.",
    holeCards: [{ rank: "K", suit: "spades" }, { rank: "Q", suit: "spades" }],
  },
  {
    id: "pos-11",
    difficulty: "spade",
    scenario: "6인 테이블에서 각 포지션의 일반적인 오픈 레이즈 레인지 비율이 궁금합니다.",
    question: "포지션별 오픈 레인지가 대략적으로 올바른 것은?",
    options: [
      "UTG ~15%, HJ ~20%, CO ~28%, BTN ~45%",
      "모든 포지션에서 ~25%",
      "UTG ~40%, HJ ~35%, CO ~30%, BTN ~20%",
      "UTG ~5%, HJ ~10%, CO ~15%, BTN ~20%"
    ],
    correctIndex: 0,
    explanation: "얼리 포지션(UTG)에서는 ~15%의 좁은 레인지로, 레이트 포지션(BTN)에서는 ~45%의 넓은 레인지로 오픈합니다. 포지션이 좋을수록 뒤에 남은 플레이어가 적고 포스트플롭 우위가 있어 더 많은 핸드를 수익적으로 플레이할 수 있습니다. 이 레인지 비율을 이해하면 각 포지션에서 적절한 핸드를 선택하는 데 도움이 됩니다.",
    hint: "포지션이 뒤(레이트)일수록 오픈 레인지가 넓어집니다.",
  },
  {
    id: "pos-12",
    difficulty: "spade",
    scenario: "멀티웨이 팟에서 당신은 HJ에서 콜한 후 BTN, SB도 콜했습니다. 플롭이 나왔습니다.",
    question: "멀티웨이 팟에서 포지션이 더 중요한 이유는?",
    options: [
      "여러 플레이어의 행동을 모두 관찰한 후 결정할 수 있어 정보가 훨씬 많다",
      "멀티웨이에서는 포지션이 덜 중요하다",
      "멀티웨이에서는 항상 체크해야 한다",
      "BTN은 멀티웨이에서 불리하다"
    ],
    correctIndex: 0,
    explanation: "멀티웨이 팟에서 IP(인 포지션)는 모든 플레이어의 체크/베팅을 관찰한 후 결정합니다. 더 많은 정보를 바탕으로 블러프, 밸류벳, 체크백을 정확하게 선택할 수 있어 포지셔널 어드밴티지가 헤즈업보다 더 커집니다. 따라서 멀티웨이 팟에서는 포지션이 좋을수록 더 넓은 레인지로 참여할 수 있습니다.",
    hint: "관찰할 플레이어가 많을수록 IP의 정보 우위가 커집니다.",
  },
];

export const handRankingQuestions: QuizQuestion[] = [
  {
    id: "hr-1",
    difficulty: "club",
    scenario: "당신의 홀카드는 A♠K♠이고 보드는 A♥J♦7♣2♠9♦입니다.",
    question: "당신이 만든 최고의 핸드(족보)는?",
    options: ["에이스 투 페어", "에이스 원 페어 + 킹 킥커", "에이스 하이", "플러시"],
    correctIndex: 1,
    explanation: "A♠K♠ + 보드 A♥J♦7♣2♠9♦: 에이스 페어(A♠+A♥)에 킹 킥커(최선 5장: AAK J 9). 스페이드가 2장뿐이라 플러시는 불가하고, 보드에 페어가 없어 투 페어도 불가합니다. 이 핸드는 '탑 페어 탑 킥커(TPTK)'라 불리며, 원 페어 중 가장 강한 형태로 실전에서 자주 큰 팟을 만듭니다.",
    hint: "홀카드와 보드를 합쳐 가장 좋은 5장 조합을 찾으세요.",
    holeCards: [{ rank: "A", suit: "spades" }, { rank: "K", suit: "spades" }],
    boardCards: [{ rank: "A", suit: "hearts" }, { rank: "J", suit: "diamonds" }, { rank: "7", suit: "clubs" }, { rank: "2", suit: "spades" }, { rank: "9", suit: "diamonds" }],
  },
  {
    id: "hr-2",
    difficulty: "club",
    scenario: "텍사스 홀덤의 족보를 순서대로 외우고 있습니다.",
    question: "다음 중 족보 순위가 높은 것부터 낮은 순서로 올바른 것은?",
    options: [
      "로열 플러시 > 스트레이트 플러시 > 포카드 > 풀하우스 > 플러시",
      "로열 플러시 > 포카드 > 스트레이트 플러시 > 풀하우스 > 플러시",
      "풀하우스 > 플러시 > 스트레이트 > 포카드 > 트리플",
      "스트레이트 플러시 > 로열 플러시 > 포카드 > 풀하우스 > 플러시"
    ],
    correctIndex: 0,
    explanation: "족보 순위 (높은 순): 로열 플러시 > 스트레이트 플러시 > 포카드 > 풀하우스 > 플러시 > 스트레이트 > 트리플(쓰리오브어카인드) > 투 페어 > 원 페어 > 하이카드. 만들기 어려운 조합일수록 높은 순위입니다. 이 순서를 정확히 암기해야 쇼다운에서 승패를 판단할 수 있습니다.",
    hint: "같은 무늬 5장(플러시)이 연속 숫자(스트레이트)보다 높습니다.",
  },
  {
    id: "hr-8",
    difficulty: "club",
    scenario: "홀카드 K♥J♣, 보드 9♦4♠2♥7♣5♦.",
    question: "이 핸드의 족보는?",
    options: ["원 페어", "킹 하이카드", "스트레이트", "투 페어"],
    correctIndex: 1,
    explanation: "K♥J♣ + 보드 9♦4♠2♥7♣5♦: 페어, 플러시, 스트레이트 모두 없습니다. 최선의 5장은 KJ975(킹 하이카드)입니다. 7장 중 어떤 조합으로도 족보를 만들 수 없으면 가장 높은 카드를 기준으로 하이카드가 됩니다. 하이카드는 가장 약한 족보이므로, 실전에서는 블러프 없이 쇼다운까지 가면 거의 이기기 어렵습니다.",
    hint: "페어도 없고 5장 연속이나 같은 무늬 5장도 없으면 하이카드입니다.",
    holeCards: [{ rank: "K", suit: "hearts" }, { rank: "J", suit: "clubs" }],
    boardCards: [{ rank: "9", suit: "diamonds" }, { rank: "4", suit: "spades" }, { rank: "2", suit: "hearts" }, { rank: "7", suit: "clubs" }, { rank: "5", suit: "diamonds" }],
  },
  {
    id: "hr-3",
    difficulty: "diamond",
    scenario: "홀카드 Q♥Q♦, 보드 Q♠8♣8♥5♦2♣.",
    question: "이 핸드의 족보는?",
    options: ["트리플(쓰리오브어카인드)", "풀하우스", "투 페어", "포카드"],
    correctIndex: 1,
    explanation: "Q♥Q♦ + 보드 Q♠8♣8♥: 최선의 5장은 QQQ88(퀸 풀하우스). 풀하우스는 '트리플 + 페어'로 구성되며, 플러시와 스트레이트보다 높은 강력한 족보입니다. 실전에서 풀하우스는 큰 팟을 노릴 수 있는 핸드입니다.",
    hint: "홀카드와 보드를 합쳐 같은 숫자 3장 + 같은 숫자 2장이 있는지 확인하세요.",
    holeCards: [{ rank: "Q", suit: "hearts" }, { rank: "Q", suit: "diamonds" }],
    boardCards: [{ rank: "Q", suit: "spades" }, { rank: "8", suit: "clubs" }, { rank: "8", suit: "hearts" }, { rank: "5", suit: "diamonds" }, { rank: "2", suit: "clubs" }],
  },
  {
    id: "hr-4",
    difficulty: "diamond",
    scenario: "홀카드 T♠9♠, 보드 7♠8♠J♣K♦2♥.",
    question: "이 핸드의 족보는?",
    options: ["스트레이트 (7-8-9-T-J)", "플러시", "하이카드", "원 페어"],
    correctIndex: 0,
    explanation: "T♠9♠ + 보드 7♠8♠J♣K♦2♥: 최선의 5장은 789TJ(잭하이 스트레이트). 스페이드가 4장(T♠9♠7♠8♠)이지만 5장이 아니므로 플러시는 아닙니다. 스트레이트를 정확히 식별하려면 7장 중 연속 5장이 있는지 확인하세요.",
    hint: "5장 연속 숫자가 있는지 먼저 확인하세요.",
    holeCards: [{ rank: "T", suit: "spades" }, { rank: "9", suit: "spades" }],
    boardCards: [{ rank: "7", suit: "spades" }, { rank: "8", suit: "spades" }, { rank: "J", suit: "clubs" }, { rank: "K", suit: "diamonds" }, { rank: "2", suit: "hearts" }],
  },
  {
    id: "hr-12",
    difficulty: "diamond",
    scenario: "홀카드 K♠T♠, 보드 K♦T♥5♣9♠3♦.",
    question: "이 핸드의 족보는?",
    options: ["원 페어(킹 페어)", "투 페어(킹+텐)", "풀하우스", "스트레이트"],
    correctIndex: 1,
    explanation: "K♠T♠ + 보드 K♦T♥5♣9♠3♦: 최선의 5장은 KKTT9(킹+텐 투 페어). 투 페어 비교는 높은 페어부터 하고, 같으면 낮은 페어, 그래도 같으면 킥커로 결정합니다. 실전에서 투 페어는 강한 핸드지만, 보드가 위험할 때(스트레이트/플러시 가능) 과신하면 안 됩니다.",
    hint: "홀카드 두 장 모두 보드와 매칭되면 투 페어입니다.",
    holeCards: [{ rank: "K", suit: "spades" }, { rank: "T", suit: "spades" }],
    boardCards: [{ rank: "K", suit: "diamonds" }, { rank: "T", suit: "hearts" }, { rank: "5", suit: "clubs" }, { rank: "9", suit: "spades" }, { rank: "3", suit: "diamonds" }],
  },
  {
    id: "hr-5",
    difficulty: "heart",
    scenario: "홀카드 5♥5♣, 보드 A♠K♠Q♦J♣T♥.",
    question: "당신의 최고 핸드(최선의 5장 조합)는?",
    options: ["포켓 파이브(원 페어)", "에이스 하이 스트레이트(브로드웨이)", "에이스 하이", "투 페어"],
    correctIndex: 1,
    explanation: "보드 A♠K♠Q♦J♣T♥는 이미 AKQJT 브로드웨이 스트레이트를 구성합니다. 최선의 5장은 보드 전체(AKQJT)이며, 홀카드 5♥5♣(원 페어)는 이보다 약해 사용되지 않습니다. 보드 자체가 강한 핸드를 이룰 때 홀카드가 무의미해질 수 있다는 점을 기억하세요.",
    hint: "7장(홀카드2+보드5) 중 최고 5장 조합을 찾으세요. 보드 자체가 답일 수 있습니다.",
    holeCards: [{ rank: "5", suit: "hearts" }, { rank: "5", suit: "clubs" }],
    boardCards: [{ rank: "A", suit: "spades" }, { rank: "K", suit: "spades" }, { rank: "Q", suit: "diamonds" }, { rank: "J", suit: "clubs" }, { rank: "T", suit: "hearts" }],
  },
  {
    id: "hr-6",
    difficulty: "heart",
    scenario: "홀카드 A♦3♦, 보드 K♦8♦5♦J♠2♣.",
    question: "이 핸드의 족보는?",
    options: ["에이스 하이", "플러시", "스트레이트", "원 페어"],
    correctIndex: 1,
    explanation: "A♦3♦ + 보드 K♦8♦5♦J♠2♣: 최선의 5장은 A♦K♦8♦5♦3♦(에이스 하이 플러시, 넛 플러시). 같은 무늬 5장 이상이면 플러시이며, 가장 높은 카드로 순위를 비교합니다. 에이스 하이 플러시는 넛(최강) 플러시이므로 실전에서 자신 있게 밸류벳할 수 있습니다.",
    hint: "같은 무늬(suit)가 5장 이상이면 플러시입니다.",
    holeCards: [{ rank: "A", suit: "diamonds" }, { rank: "3", suit: "diamonds" }],
    boardCards: [{ rank: "K", suit: "diamonds" }, { rank: "8", suit: "diamonds" }, { rank: "5", suit: "diamonds" }, { rank: "J", suit: "spades" }, { rank: "2", suit: "clubs" }],
  },
  {
    id: "hr-10",
    difficulty: "heart",
    scenario: "홀카드 9♥9♦, 보드 K♠J♦9♣4♥2♠.",
    question: "이 핸드의 족보와 강도를 평가하세요.",
    options: [
      "셋(쓰리오브어카인드) — 숨겨진 셋으로 매우 강하다",
      "원 페어 — 나인 페어로 약하다",
      "투 페어 — 나인과 킹 페어",
      "풀하우스"
    ],
    correctIndex: 0,
    explanation: "9♥9♦ + 보드 K♠J♦9♣4♥2♠: 최선의 5장은 999KJ(나인 셋). 홀카드 포켓 페어가 보드의 한 장과 맞으면 '셋'이라 부릅니다. 셋은 상대가 알아채기 어려운 '숨겨진' 핸드여서 큰 팟을 따낼 수 있는 강력한 족보입니다.",
    hint: "포켓 페어 + 보드 매칭 = 셋(Set)",
    holeCards: [{ rank: "9", suit: "hearts" }, { rank: "9", suit: "diamonds" }],
    boardCards: [{ rank: "K", suit: "spades" }, { rank: "J", suit: "diamonds" }, { rank: "9", suit: "clubs" }, { rank: "4", suit: "hearts" }, { rank: "2", suit: "spades" }],
  },
  {
    id: "hr-7",
    difficulty: "spade",
    scenario: "플레이어A: Q♠J♣. 플레이어B: K♦T♣. 보드: Q♥Q♦T♠T♥3♣. 두 플레이어 모두 풀하우스를 가지고 있습니다.",
    question: "누가 이깁니까?",
    options: [
      "플레이어A: QQQ TT (퀸 풀하우스) 승리",
      "플레이어B: TTT QQ (텐 풀하우스) 승리",
      "무승부 — 둘 다 풀하우스",
      "플레이어B: KT로 킹 킥커 승리"
    ],
    correctIndex: 0,
    explanation: "풀하우스끼리 비교할 때는 트리플(3장) 부분의 숫자를 먼저 비교합니다. 플레이어A: Q♠ + Q♥Q♦(보드) = QQQ, 페어 T♠T♥ → QQQ TT. 플레이어B: T♣ + T♠T♥(보드) = TTT, 페어 Q♥Q♦ → TTT QQ. Q > T이므로 플레이어A 승리. 풀하우스에서 페어 부분이 아무리 높아도 트리플 부분이 더 높은 쪽이 이기므로, '어떤 3장을 가졌는가'가 핵심입니다.",
    hint: "풀하우스끼리는 트리플(3장) 부분의 숫자가 높은 쪽이 이깁니다.",
    playerHands: [
      { label: "플레이어A", cards: [{ rank: "Q", suit: "spades" }, { rank: "J", suit: "clubs" }] },
      { label: "플레이어B", cards: [{ rank: "K", suit: "diamonds" }, { rank: "T", suit: "clubs" }] },
    ],
    boardCards: [{ rank: "Q", suit: "hearts" }, { rank: "Q", suit: "diamonds" }, { rank: "T", suit: "spades" }, { rank: "T", suit: "hearts" }, { rank: "3", suit: "clubs" }],
  },
  {
    id: "hr-9",
    difficulty: "spade",
    scenario: "플레이어A: A♠9♣. 플레이어B: A♦8♠. 보드: A♥K♣K♦5♠2♣. 두 플레이어 모두 에이스-킹 투 페어입니다.",
    question: "승자는?",
    options: [
      "무승부 — 둘 다 AA KK 투 페어",
      "플레이어A: 킥커 9 > 8로 승리",
      "플레이어B: 스페이드가 더 많아 승리",
      "보드 카드로만 결정 — 킥커 5"
    ],
    correctIndex: 1,
    explanation: "두 플레이어의 최선의 5장을 비교합니다. A: AA KK 9(킥커). B: AA KK 8(킥커). 투 페어가 동일(AA KK)하므로 5번째 카드(킥커)로 승부합니다. 9 > 8이므로 플레이어A 승리. 같은 투 페어에서 킥커 1장 차이가 승패를 결정하는 상황은 실전에서 자주 발생하며, 특히 홀카드의 두 번째 카드(사이드 카드)가 중요한 이유입니다.",
    hint: "투 페어가 같으면 5번째 카드(킥커)로 비교합니다.",
    playerHands: [
      { label: "플레이어A", cards: [{ rank: "A", suit: "spades" }, { rank: "9", suit: "clubs" }] },
      { label: "플레이어B", cards: [{ rank: "A", suit: "diamonds" }, { rank: "8", suit: "spades" }] },
    ],
    boardCards: [{ rank: "A", suit: "hearts" }, { rank: "K", suit: "clubs" }, { rank: "K", suit: "diamonds" }, { rank: "5", suit: "spades" }, { rank: "2", suit: "clubs" }],
  },
  {
    id: "hr-11",
    difficulty: "spade",
    scenario: "홀카드 A♣K♣. 보드1: A♠K♦Q♥J♣T♠. 보드2: A♠K♦7♥3♣2♠. 같은 AK이지만 보드에 따라 핸드 가치가 달라집니다.",
    question: "두 보드에서 AK의 가치 차이를 올바르게 평가하면?",
    options: [
      "보드1이 더 강하다 — 투 페어 + 스트레이트",
      "보드2에서 AK는 탑 투 페어로 매우 강하지만, 보드1에서는 모든 플레이어가 보드 스트레이트(AKQJT)를 공유해 AK 투 페어의 가치가 사라진다",
      "두 보드 모두 동일 — AK는 어디서든 탑 투 페어",
      "보드1이 무조건 유리 — 카드가 크면 좋다"
    ],
    correctIndex: 1,
    explanation: "보드2(A♠K♦7♥3♣2♠)에서 AK는 탑 투 페어(AAKK7)로 넛급 핸드입니다. 하지만 보드1(A♠K♦Q♥J♣T♠)에서는 보드 자체가 AKQJT 브로드웨이 스트레이트를 구성하므로, 모든 플레이어가 이 스트레이트를 공유합니다. AK의 투 페어는 스트레이트보다 낮아 의미가 없고, 홀카드와 무관하게 누구나 동일한 최선의 5장(AKQJT)을 갖게 됩니다. '보드 텍스처가 핸드의 상대적 가치를 결정한다'는 핵심 개념입니다.",
    hint: "보드가 이미 강한 핸드를 구성하면 홀카드의 가치가 어떻게 변하나요?",
    holeCards: [{ rank: "A", suit: "clubs" }, { rank: "K", suit: "clubs" }],
  },
];

export const showdownQuestions: QuizQuestion[] = [
  {
    id: "sd-1",
    difficulty: "club",
    scenario: "리버 쇼다운. 플레이어A: A♠K♥ (에이스 페어). 플레이어B: Q♦Q♣ (퀸 페어). 보드: A♦9♠7♣4♥2♦.",
    question: "승자는 누구입니까?",
    options: ["플레이어A (에이스 페어)", "플레이어B (퀸 페어)", "무승부", "보드에 따라 다름"],
    correctIndex: 0,
    explanation: "플레이어A의 최선의 5장: AAK97(에이스 페어+킹 킥커). 플레이어B의 최선의 5장: QQA97(퀸 페어). 원 페어끼리는 페어 숫자가 높은 쪽이 이깁니다. 에이스 > 퀸이므로 플레이어A 승리. 실전에서 탑 페어(보드 최고 카드와 매칭)는 큰 강점이 됩니다.",
    hint: "같은 족보(원 페어)끼리는 숫자가 높은 쪽이 이깁니다.",
    holeCards: [{ rank: "A", suit: "spades" }, { rank: "K", suit: "hearts" }],
    boardCards: [{ rank: "A", suit: "diamonds" }, { rank: "9", suit: "spades" }, { rank: "7", suit: "clubs" }, { rank: "4", suit: "hearts" }, { rank: "2", suit: "diamonds" }],
    playerHands: [
      { label: "플레이어A", cards: [{ rank: "A", suit: "spades" }, { rank: "K", suit: "hearts" }] },
      { label: "플레이어B", cards: [{ rank: "Q", suit: "diamonds" }, { rank: "Q", suit: "clubs" }] },
    ],
  },
  {
    id: "sd-13",
    difficulty: "club",
    scenario: "리버 쇼다운. 플레이어A: 9♠9♦ (나인 투 페어). 플레이어B: A♣K♦ (에이스 킹 하이카드). 보드: 9♥6♣3♠J♦2♥.",
    question: "승자는?",
    options: [
      "플레이어A: 나인 셋(쓰리오브어카인드) 승리",
      "플레이어B: 에이스 킹 하이카드 승리",
      "무승부",
      "플레이어B: 잭 페어 승리"
    ],
    correctIndex: 0,
    explanation: "플레이어A의 최선의 5장: 999J6(나인 셋). 홀카드 99 + 보드 9♥로 쓰리오브어카인드(셋)가 완성됩니다. 플레이어B의 최선의 5장: AKJ96(에이스 킹 하이카드). 셋은 원 페어, 투 페어는 물론 하이카드보다 훨씬 높은 족보이므로 플레이어A가 압도적으로 승리합니다.",
    hint: "족보 순위: 셋(쓰리오브어카인드) > 투 페어 > 원 페어 > 하이카드",
    holeCards: [{ rank: "9", suit: "spades" }, { rank: "9", suit: "diamonds" }],
    boardCards: [{ rank: "9", suit: "hearts" }, { rank: "6", suit: "clubs" }, { rank: "3", suit: "spades" }, { rank: "J", suit: "diamonds" }, { rank: "2", suit: "hearts" }],
    playerHands: [
      { label: "플레이어A", cards: [{ rank: "9", suit: "spades" }, { rank: "9", suit: "diamonds" }] },
      { label: "플레이어B", cards: [{ rank: "A", suit: "clubs" }, { rank: "K", suit: "diamonds" }] },
    ],
  },
  {
    id: "sd-8",
    difficulty: "diamond",
    scenario: "리버 쇼다운. 플레이어A: 6♠5♠. 플레이어B: T♥9♥. 보드: 7♣8♦4♠J♣2♦.",
    question: "승자는?",
    options: [
      "플레이어A: 8하이 스트레이트 승리",
      "스트레이트끼리는 항상 무승부",
      "둘 다 스트레이트가 아님 — 하이카드로 결정",
      "플레이어B: 잭하이 스트레이트 승리 (높은 탑 카드)"
    ],
    correctIndex: 3,
    explanation: "플레이어A의 최선의 5장: 45678(8하이 스트레이트). 플레이어B의 최선의 5장: 789TJ(잭하이 스트레이트). 스트레이트끼리는 가장 높은 카드(탑 카드)로 비교합니다. J > 8이므로 플레이어B 승리. 같은 보드에서 다른 높이의 스트레이트가 만들어질 수 있으므로, 넛 스트레이트인지 확인하는 습관이 중요합니다.",
    hint: "스트레이트끼리는 탑 카드가 높은 쪽이 이깁니다.",
    holeCards: [{ rank: "6", suit: "spades" }, { rank: "5", suit: "spades" }],
    boardCards: [{ rank: "7", suit: "clubs" }, { rank: "8", suit: "diamonds" }, { rank: "4", suit: "spades" }, { rank: "J", suit: "clubs" }, { rank: "2", suit: "diamonds" }],
    playerHands: [
      { label: "플레이어A", cards: [{ rank: "6", suit: "spades" }, { rank: "5", suit: "spades" }] },
      { label: "플레이어B", cards: [{ rank: "T", suit: "hearts" }, { rank: "9", suit: "hearts" }] },
    ],
  },
  {
    id: "sd-2",
    difficulty: "diamond",
    scenario: "리버 쇼다운. 플레이어A: A♠K♠. 플레이어B: A♥Q♥. 보드: A♦J♣8♠4♥2♦.",
    question: "두 플레이어 모두 에이스 페어인데 승자는?",
    options: ["무승부 (같은 에이스 페어)", "플레이어A (킹 킥커)", "플레이어B (퀸 킥커)", "보드 카드로 결정"],
    correctIndex: 1,
    explanation: "둘 다 에이스 페어이므로 킥커로 비교합니다. 플레이어A의 최선의 5장: AAKJ8. 플레이어B의 최선의 5장: AAQJ8. 킹 > 퀸이므로 플레이어A가 킥커로 승리합니다. 킥커 승부는 실전에서 매우 자주 발생하므로, 홀카드의 두 번째 카드도 핸드 선택 시 중요합니다.",
    hint: "같은 페어면 킥커(나머지 카드 중 가장 높은 카드)로 비교합니다.",
    holeCards: [{ rank: "A", suit: "spades" }, { rank: "K", suit: "spades" }],
    boardCards: [{ rank: "A", suit: "diamonds" }, { rank: "J", suit: "clubs" }, { rank: "8", suit: "spades" }, { rank: "4", suit: "hearts" }, { rank: "2", suit: "diamonds" }],
    playerHands: [
      { label: "플레이어A", cards: [{ rank: "A", suit: "spades" }, { rank: "K", suit: "spades" }] },
      { label: "플레이어B", cards: [{ rank: "A", suit: "hearts" }, { rank: "Q", suit: "hearts" }] },
    ],
  },
  {
    id: "sd-4",
    difficulty: "diamond",
    scenario: "리버 쇼다운. 플레이어A: 7♠7♥ (세븐 페어). 플레이어B: A♠K♣ (에이스 킹 하이카드). 보드: Q♦J♣8♠4♥2♦.",
    question: "승자는?",
    options: ["플레이어B (에이스 킹 하이)", "플레이어A (세븐 페어)", "무승부", "하이카드가 항상 이긴다"],
    correctIndex: 1,
    explanation: "원 페어는 하이카드보다 높은 족보입니다. 세븐 페어(77QJ8)가 에이스 킹 하이카드(AKQJ8)를 이깁니다. 초보자는 AK 같은 높은 카드에 현혹되기 쉽지만, 족보 순위상 가장 작은 페어(22)도 에이스 하이카드를 이깁니다.",
    hint: "어떤 페어든 하이카드보다 높습니다.",
    holeCards: [{ rank: "7", suit: "spades" }, { rank: "7", suit: "hearts" }],
    boardCards: [{ rank: "Q", suit: "diamonds" }, { rank: "J", suit: "clubs" }, { rank: "8", suit: "spades" }, { rank: "4", suit: "hearts" }, { rank: "2", suit: "diamonds" }],
    playerHands: [
      { label: "플레이어A", cards: [{ rank: "7", suit: "spades" }, { rank: "7", suit: "hearts" }] },
      { label: "플레이어B", cards: [{ rank: "A", suit: "spades" }, { rank: "K", suit: "clubs" }] },
    ],
  },
  {
    id: "sd-5",
    difficulty: "diamond",
    scenario: "리버 쇼다운. 플레이어A: A♠9♣. 플레이어B: A♥9♦. 보드: A♦K♣T♠7♥3♦.",
    question: "승자는?",
    options: ["플레이어A — 스페이드 에이스가 더 높다", "플레이어B", "무승부 (팟 분할)", "보드 카드로 결정"],
    correctIndex: 2,
    explanation: "플레이어A의 최선의 5장: AAK T 9. 플레이어B의 최선의 5장: AAK T 9. 최선의 5장이 완전히 동일하므로 무승부(팟 분할)입니다. 텍사스 홀덤에서 수트(무늬)는 족보 비교에 사용되지 않으므로, A♠와 A♥는 동등합니다. 같은 숫자의 홀카드를 가진 경우 스플릿 팟이 자주 발생하며, 이때 수트로 승패를 가리지 않는다는 규칙을 기억하세요.",
    hint: "텍사스 홀덤에서 무늬(수트)로 승패를 가리지 않습니다.",
    holeCards: [{ rank: "A", suit: "spades" }, { rank: "9", suit: "clubs" }],
    boardCards: [{ rank: "A", suit: "diamonds" }, { rank: "K", suit: "clubs" }, { rank: "T", suit: "spades" }, { rank: "7", suit: "hearts" }, { rank: "3", suit: "diamonds" }],
    playerHands: [
      { label: "플레이어A", cards: [{ rank: "A", suit: "spades" }, { rank: "9", suit: "clubs" }] },
      { label: "플레이어B", cards: [{ rank: "A", suit: "hearts" }, { rank: "9", suit: "diamonds" }] },
    ],
  },
  {
    id: "sd-9",
    difficulty: "diamond",
    scenario: "리버 쇼다운. 3명이 남아있습니다. 플레이어A: K♠Q♠. 플레이어B: K♥J♥. 플레이어C: K♦T♦. 보드: K♣9♠5♥3♦2♣.",
    question: "3명 모두 킹 페어인데 순위는?",
    options: [
      "A(킹+퀸킥커) > B(킹+잭킥커) > C(킹+텐킥커)",
      "무승부 — 같은 킹 페어",
      "C > B > A (역순)",
      "보드 카드로만 결정"
    ],
    correctIndex: 0,
    explanation: "모두 킹 페어. 최선의 5장 비교: A는 KKQ95, B는 KKJ95, C는 KKT95. 킥커: Q > J > T이므로 순위는 A > B > C. 플레이어A가 전체 팟을 가져갑니다. 멀티웨이에서 같은 페어가 겹치면 킥커 한 장이 팟 전체를 결정합니다.",
    hint: "같은 페어면 킥커(다음으로 높은 카드)로 순위를 정합니다.",
    holeCards: [{ rank: "K", suit: "spades" }, { rank: "Q", suit: "spades" }],
    boardCards: [{ rank: "K", suit: "clubs" }, { rank: "9", suit: "spades" }, { rank: "5", suit: "hearts" }, { rank: "3", suit: "diamonds" }, { rank: "2", suit: "clubs" }],
    playerHands: [
      { label: "플레이어A", cards: [{ rank: "K", suit: "spades" }, { rank: "Q", suit: "spades" }] },
      { label: "플레이어B", cards: [{ rank: "K", suit: "hearts" }, { rank: "J", suit: "hearts" }] },
      { label: "플레이어C", cards: [{ rank: "K", suit: "diamonds" }, { rank: "T", suit: "diamonds" }] },
    ],
  },
  {
    id: "sd-3",
    difficulty: "heart",
    scenario: "리버 쇼다운. 플레이어A: K♠K♥. 플레이어B: A♦A♣. 보드: K♦A♠9♣5♥3♦.",
    question: "두 플레이어 모두 셋(쓰리오브어카인드)을 만들었습니다. 승자는?",
    options: ["플레이어A (킹 셋으로 승리)", "플레이어B (에이스 셋으로 승리)", "무승부", "킥커로 결정"],
    correctIndex: 1,
    explanation: "플레이어A의 최선의 5장: KKKA9(킹 셋). 플레이어B의 최선의 5장: AAAK9(에이스 셋). 같은 족보(셋)끼리는 트리플의 숫자가 높은 쪽이 이깁니다. 에이스 > 킹이므로 플레이어B 승리. 셋 vs 셋은 드문 상황이지만, 발생 시 매우 큰 팟이 만들어집니다.",
    hint: "포켓 페어가 보드와 매칭되면 셋(쓰리오브어카인드)입니다.",
    holeCards: [{ rank: "K", suit: "spades" }, { rank: "K", suit: "hearts" }],
    boardCards: [{ rank: "K", suit: "diamonds" }, { rank: "A", suit: "spades" }, { rank: "9", suit: "clubs" }, { rank: "5", suit: "hearts" }, { rank: "3", suit: "diamonds" }],
    playerHands: [
      { label: "플레이어A", cards: [{ rank: "K", suit: "spades" }, { rank: "K", suit: "hearts" }] },
      { label: "플레이어B", cards: [{ rank: "A", suit: "diamonds" }, { rank: "A", suit: "clubs" }] },
    ],
  },
  {
    id: "sd-6",
    difficulty: "heart",
    scenario: "리버 쇼다운. 플레이어A: 8♠8♥. 플레이어B: A♣K♦. 보드: Q♠Q♥J♣J♦3♠.",
    question: "승자와 각 플레이어의 최종 핸드는?",
    options: [
      "플레이어A: QQ88J(투 페어+킥커) 승리",
      "플레이어B: QQJJA(투 페어+에이스 킥커) 승리",
      "플레이어A: QQ88(투 페어) vs B: QQJJ(투 페어) → B 승리",
      "무승부 — 보드 투 페어 공유"
    ],
    correctIndex: 1,
    explanation: "텍사스 홀덤은 최선의 5장으로 판단합니다. 보드에 이미 QQ+JJ 투 페어가 있으므로 양쪽 모두 이 투 페어를 공유합니다. 플레이어A의 88은 QQ·JJ보다 낮아 투 페어에 포함되지 않고, 5번째 카드(킥커)로만 작용하여 QQJJ8이 됩니다. 플레이어B는 에이스를 킥커로 사용해 QQJJA가 됩니다. A > 8이므로 플레이어B 승리. 보드 페어보다 낮은 포켓 페어는 킥커 역할밖에 못한다는 점이 핵심입니다.",
    hint: "최선의 5장 기준으로 생각하세요. 보드에 높은 투 페어가 있으면 낮은 포켓 페어의 역할이 무엇일까요?",
    holeCards: [{ rank: "8", suit: "spades" }, { rank: "8", suit: "hearts" }],
    boardCards: [{ rank: "Q", suit: "spades" }, { rank: "Q", suit: "hearts" }, { rank: "J", suit: "clubs" }, { rank: "J", suit: "diamonds" }, { rank: "3", suit: "spades" }],
    playerHands: [
      { label: "플레이어A", cards: [{ rank: "8", suit: "spades" }, { rank: "8", suit: "hearts" }] },
      { label: "플레이어B", cards: [{ rank: "A", suit: "clubs" }, { rank: "K", suit: "diamonds" }] },
    ],
  },
  {
    id: "sd-7",
    difficulty: "heart",
    scenario: "리버 쇼다운. 플레이어A: K♠K♦. 플레이어B: 9♣9♠. 보드: A♠A♥A♦7♣2♥.",
    question: "보드에 에이스 트리플이 있을 때 승자는?",
    options: [
      "무승부 — 보드 에이스 트리플 공유",
      "플레이어A: AAAKK(풀하우스) 승리",
      "플레이어B: AAA99(풀하우스) 승리",
      "높은 킥커가 결정 — A와 비교"
    ],
    correctIndex: 1,
    explanation: "플레이어A의 최선의 5장: AAAKK(에이스 풀하우스). 플레이어B의 최선의 5장: AAA99(에이스 풀하우스). 풀하우스끼리는 트리플이 같으면 페어로 비교합니다. KK > 99이므로 플레이어A 승리. 보드에 트리플이 있을 때 높은 포켓 페어가 큰 가치를 가집니다.",
    hint: "풀하우스끼리는 트리플 먼저, 같으면 페어 비교.",
    holeCards: [{ rank: "K", suit: "spades" }, { rank: "K", suit: "diamonds" }],
    boardCards: [{ rank: "A", suit: "spades" }, { rank: "A", suit: "hearts" }, { rank: "A", suit: "diamonds" }, { rank: "7", suit: "clubs" }, { rank: "2", suit: "hearts" }],
    playerHands: [
      { label: "플레이어A", cards: [{ rank: "K", suit: "spades" }, { rank: "K", suit: "diamonds" }] },
      { label: "플레이어B", cards: [{ rank: "9", suit: "clubs" }, { rank: "9", suit: "spades" }] },
    ],
  },
  {
    id: "sd-10",
    difficulty: "heart",
    scenario: "리버 쇼다운. 플레이어A: 2♠3♠. 플레이어B: A♣K♣. 보드: 4♠5♠6♠7♠J♦.",
    question: "승자와 이유는?",
    options: [
      "플레이어B: 에이스 킹 하이카드 승리",
      "플레이어A: 7하이 스트레이트 플러시(3♠-4♠-5♠-6♠-7♠) 승리",
      "플레이어A: 스페이드 플러시 승리",
      "무승부"
    ],
    correctIndex: 1,
    explanation: "플레이어A의 최선의 5장: 3♠4♠5♠6♠7♠(7하이 스트레이트 플러시). 플레이어B의 최선의 5장: AKJ76(에이스 킹 하이카드). 스트레이트 플러시는 포카드보다 높은 최상위 족보입니다. 실전에서 스트레이트 플러시는 극히 드물며, 만들면 최대한 팟을 키우는 것이 목표입니다.",
    hint: "같은 무늬의 연속 숫자 5장 = 스트레이트 플러시",
    holeCards: [{ rank: "2", suit: "spades" }, { rank: "3", suit: "spades" }],
    boardCards: [{ rank: "4", suit: "spades" }, { rank: "5", suit: "spades" }, { rank: "6", suit: "spades" }, { rank: "7", suit: "spades" }, { rank: "J", suit: "diamonds" }],
    playerHands: [
      { label: "플레이어A", cards: [{ rank: "2", suit: "spades" }, { rank: "3", suit: "spades" }] },
      { label: "플레이어B", cards: [{ rank: "A", suit: "clubs" }, { rank: "K", suit: "clubs" }] },
    ],
  },
  {
    id: "sd-11",
    difficulty: "heart",
    scenario: "리버. 플레이어A: J♠T♠. 플레이어B: J♥T♥. 보드: J♦T♣5♠5♥3♦.",
    question: "승자는?",
    options: [
      "플레이어A (스페이드 수트가 높다)",
      "플레이어B (하트 수트가 높다)",
      "무승부 — 동일한 투 페어(JJTT5)",
      "A가 스페이드 백도어 플러시로 승리"
    ],
    correctIndex: 2,
    explanation: "플레이어A의 최선의 5장: JJTT5(잭+텐 투 페어). 플레이어B의 최선의 5장: JJTT5(동일). 최선의 5장이 완전히 같으므로 무승부(팟 분할)입니다. 텍사스 홀덤에서 수트는 핸드 순위에 영향을 주지 않으므로 ♠와 ♥의 차이는 없습니다. 이 규칙을 정확히 알아야 스플릿 팟을 올바르게 판단할 수 있습니다.",
    hint: "최선의 5장 조합이 완전히 동일하면 무승부입니다.",
    holeCards: [{ rank: "J", suit: "spades" }, { rank: "T", suit: "spades" }],
    boardCards: [{ rank: "J", suit: "diamonds" }, { rank: "T", suit: "clubs" }, { rank: "5", suit: "spades" }, { rank: "5", suit: "hearts" }, { rank: "3", suit: "diamonds" }],
    playerHands: [
      { label: "플레이어A", cards: [{ rank: "J", suit: "spades" }, { rank: "T", suit: "spades" }] },
      { label: "플레이어B", cards: [{ rank: "J", suit: "hearts" }, { rank: "T", suit: "hearts" }] },
    ],
  },
  {
    id: "sd-12",
    difficulty: "spade",
    scenario: "리버. 플레이어A: 4♣4♦. 플레이어B: A♠K♠. 보드: A♥K♦Q♣J♣T♠.",
    question: "승자와 이유는?",
    options: [
      "플레이어A: 포켓 포(44) 원 페어 승리",
      "플레이어B: AAKKQ 투 페어 승리",
      "무승부 — 보드 브로드웨이 스트레이트(AKQJT) 공유",
      "플레이어B: 에이스 킹 탑 투 페어 승리"
    ],
    correctIndex: 2,
    explanation: "보드 자체가 AKQJT(에이스 하이 스트레이트, 브로드웨이)를 구성합니다. 두 플레이어의 최선의 5장은 모두 AKQJT입니다. 홀카드(44, AK)와 관계없이 보드의 5장을 넘는 조합을 만들 수 없으므로 무승부(팟 분할). 보드가 매우 강한 핸드를 구성하면 홀카드의 가치가 사라질 수 있습니다.",
    hint: "보드가 이미 최강 5장을 구성하면 홀카드와 무관하게 무승부가 될 수 있습니다.",
    holeCards: [{ rank: "4", suit: "clubs" }, { rank: "4", suit: "diamonds" }],
    boardCards: [{ rank: "A", suit: "hearts" }, { rank: "K", suit: "diamonds" }, { rank: "Q", suit: "clubs" }, { rank: "J", suit: "clubs" }, { rank: "T", suit: "spades" }],
    playerHands: [
      { label: "플레이어A", cards: [{ rank: "4", suit: "clubs" }, { rank: "4", suit: "diamonds" }] },
      { label: "플레이어B", cards: [{ rank: "A", suit: "spades" }, { rank: "K", suit: "spades" }] },
    ],
  },
  {
    id: "sd-14",
    difficulty: "spade",
    scenario: "리버. 3명 쇼다운. 플레이어A: K♠Q♦. 플레이어B: K♦Q♣. 플레이어C: A♠2♠. 보드: K♥Q♥J♠T♦9♣.",
    question: "승자는?",
    options: [
      "A와 B 동점 — 둘 다 KQ 투 페어",
      "3명 동점 — 보드 스트레이트(KQJT9) 공유",
      "플레이어C 승리 — A♠로 에이스 하이 스트레이트(AKQJT, 브로드웨이)",
      "플레이어A 또는 B — K 페어가 가장 높음"
    ],
    correctIndex: 2,
    explanation: "각 플레이어의 최선의 5장을 비교합니다. A와 B: K♠Q♦/K♦Q♣ + 보드 KQJT9. KK+QQ 투 페어보다 보드 스트레이트 KQJT9가 더 강합니다. 하지만 C: A♠ + 보드 KQJT = AKQJT(브로드웨이, 넛 스트레이트). A와 B의 최선 5장도 KQJT9 스트레이트이지만, C는 A를 활용해 더 높은 AKQJT 스트레이트를 만듭니다. 스트레이트끼리 탑 카드 비교: A > K이므로 C 승리. 보드에 스트레이트가 보일 때 홀카드로 더 높은 스트레이트를 만들 수 있는지가 핵심입니다.",
    hint: "보드에 연속 카드가 있을 때 홀카드로 더 높은 스트레이트를 만들 수 있는지 확인하세요.",
    playerHands: [
      { label: "플레이어A", cards: [{ rank: "K", suit: "spades" }, { rank: "Q", suit: "diamonds" }] },
      { label: "플레이어B", cards: [{ rank: "K", suit: "diamonds" }, { rank: "Q", suit: "clubs" }] },
      { label: "플레이어C", cards: [{ rank: "A", suit: "spades" }, { rank: "2", suit: "spades" }] },
    ],
    boardCards: [{ rank: "K", suit: "hearts" }, { rank: "Q", suit: "hearts" }, { rank: "J", suit: "spades" }, { rank: "T", suit: "diamonds" }, { rank: "9", suit: "clubs" }],
  },
  {
    id: "sd-15",
    difficulty: "spade",
    scenario: "리버 쇼다운. 플레이어A: A♠8♠. 플레이어B: K♠Q♠. 보드: J♠T♠4♠3♥2♦. 보드에 스페이드 3장이 깔렸습니다.",
    question: "둘 다 스페이드 플러시인데, 승자는?",
    options: [
      "무승부 — 둘 다 스페이드 플러시",
      "플레이어A: 에이스 하이 플러시(A♠J♠T♠8♠4♠) 승리",
      "플레이어B: 스트레이트 플러시 가능성으로 승리",
      "플레이어B: 킹+퀸으로 카드 2장이 더 높아 승리"
    ],
    correctIndex: 1,
    explanation: "플러시끼리 비교할 때는 가장 높은 카드부터 순서대로 비교합니다. 플레이어A의 최선 플러시: A♠J♠T♠8♠4♠(에이스 하이). 플레이어B의 최선 플러시: K♠Q♠J♠T♠4♠(킹 하이). 가장 높은 카드 A > K이므로 플레이어A 승리. B가 K+Q 두 장을 가졌더라도 에이스 1장이 그보다 높습니다. 플러시 비교의 핵심은 '가장 높은 카드'이며, 이것이 넛 플러시 드로우(에이스 포함)가 중요한 이유입니다. 넛이 아닌 플러시로 큰 팟을 만들면 더 높은 플러시에 질 위험이 있습니다.",
    hint: "플러시끼리는 가장 높은 카드부터 순서대로 비교합니다.",
    playerHands: [
      { label: "플레이어A", cards: [{ rank: "A", suit: "spades" }, { rank: "8", suit: "spades" }] },
      { label: "플레이어B", cards: [{ rank: "K", suit: "spades" }, { rank: "Q", suit: "spades" }] },
    ],
    boardCards: [{ rank: "J", suit: "spades" }, { rank: "T", suit: "spades" }, { rank: "4", suit: "spades" }, { rank: "3", suit: "hearts" }, { rank: "2", suit: "diamonds" }],
  },
];

export const minRaiseQuestions: QuizQuestion[] = [
  {
    id: "mr-1",
    difficulty: "club",
    scenario: "1/2 노리밋 홀덤. 프리플롭에서 첫 번째 레이즈를 하려고 합니다.",
    question: "최소 레이즈(민레이즈) 금액은?",
    options: ["$2 (BB와 동일)", "$4 (BB의 2배)", "$3 (BB + SB)", "$6 (BB의 3배)"],
    correctIndex: 1,
    explanation: "프리플롭 민레이즈는 BB의 2배입니다. 1/2 게임에서 BB=$2이므로 민레이즈 = $4. 계산: $2(BB 콜) + $2(인상분) = $4. 이 '이전 베팅 + 같은 금액 추가' 규칙이 모든 민레이즈의 기본 원리입니다.",
    hint: "민레이즈 = 이전 베팅 + 이전 베팅만큼의 추가 금액",
    potSize: "$3",
    betSize: "$2",
  },
  {
    id: "mr-2",
    difficulty: "club",
    scenario: "포스트플롭. 팟 $30. 상대방이 $10을 베팅했습니다. 당신이 레이즈하려 합니다.",
    question: "최소 레이즈(민레이즈) 금액은?",
    options: ["$10 (콜 금액)", "$20 (베팅의 2배)", "$30 (팟 사이즈)", "$15"],
    correctIndex: 1,
    explanation: "상대가 $10 베팅 → 민레이즈 = $10(콜) + $10(인상분) = $20. 민레이즈 규칙: 인상분은 이전 베팅/레이즈의 크기 이상이어야 합니다. 이 규칙을 알면 상대의 레이즈 합법성을 판단하고, 본인의 최소 레이즈 금액을 정확히 계산할 수 있습니다.",
    hint: "민레이즈 = 콜 금액 + 이전 베팅 금액",
    potSize: "$30",
    betSize: "$10",
  },
  {
    id: "mr-5",
    difficulty: "club",
    scenario: "노리밋 홀덤에서 '노리밋'의 의미를 이해하려 합니다.",
    question: "'노리밋'에서 최대 베팅 금액은?",
    options: [
      "팟 사이즈까지만 가능",
      "칩 스택 전체(올인)까지 제한 없음",
      "빅 블라인드의 10배까지",
      "상대 베팅의 3배까지"
    ],
    correctIndex: 1,
    explanation: "노리밋(No Limit) 홀덤에서는 언제든 보유 칩 전체를 베팅(올인)할 수 있습니다. 최소 금액(민벳/민레이즈)만 규정되어 있고 최대는 자신의 스택 전체입니다. 이것이 팟 리밋이나 리밋 홀덤과의 차이입니다.",
    hint: "'노리밋' = 최대 베팅에 제한이 없다는 뜻입니다.",
  },
  {
    id: "mr-11",
    difficulty: "club",
    scenario: "프리플롭에서 누구도 레이즈하지 않고 BB까지 왔습니다.",
    question: "BB에서 할 수 있는 액션은?",
    options: [
      "체크(추가 금액 없이 넘기기) 또는 레이즈",
      "콜만 가능",
      "폴드만 가능",
      "반드시 레이즈해야 한다"
    ],
    correctIndex: 0,
    explanation: "모두 콜(림프)하거나 폴드하면 BB는 이미 빅 블라인드를 냈으므로 추가 베팅 없이 체크할 수 있습니다. 이것을 'BB 옵션'이라 합니다. 레이즈도 가능합니다. 실전에서 BB의 체크/레이즈 결정은 림프된 팟에서 중요한 전략적 선택입니다.",
    hint: "BB는 이미 강제 베팅을 냈으므로 레이즈가 없으면 체크할 수 있습니다.",
  },
  {
    id: "mr-3",
    difficulty: "diamond",
    scenario: "프리플롭. 1/2 게임. UTG가 $6으로 레이즈합니다. 당신이 3-벳(리레이즈)하려 합니다.",
    question: "최소 3-벳 금액은?",
    options: ["$8", "$10", "$12", "$18"],
    correctIndex: 1,
    explanation: "UTG 레이즈 = $6. 인상분 = $6 - $2(BB) = $4. 민 3-벳 = $6(콜) + $4(인상분) = $10. 인상분은 이전 레이즈의 인상분 이상이어야 합니다. 이 계산을 정확히 할 수 있으면 라이브 게임에서 합법적인 3-벳 금액을 즉시 판단할 수 있습니다.",
    hint: "인상분 = 이전 레이즈 금액 - 그 전 베팅/레이즈 금액",
    potSize: "$9",
    betSize: "$6",
  },
  {
    id: "mr-4",
    difficulty: "diamond",
    scenario: "턴. 팟 $80. 플레이어A가 $40 베팅. 플레이어B가 $100으로 레이즈. 당신이 3-벳하려 합니다.",
    question: "최소 3-벳 금액은?",
    options: ["$140", "$160", "$200", "$120"],
    correctIndex: 1,
    explanation: "B의 레이즈 인상분 = $100 - $40 = $60. 최소 3-벳 = $100(콜) + $60(인상분) = $160. 각 레이즈는 최소한 이전 레이즈의 인상분만큼 더 올려야 합니다. 레이즈 체인이 길어질수록 이 계산이 복잡해지므로, 인상분 기준으로 단계적으로 계산하는 습관이 중요합니다.",
    hint: "이전 레이즈 인상분($100-$40=$60)을 콜 금액에 더하세요.",
    potSize: "$80",
    betSize: "$100",
  },
  {
    id: "mr-6",
    difficulty: "diamond",
    scenario: "포스트플롭. 팟 $50. 아무도 베팅하지 않은 상태에서 당신이 첫 베팅을 합니다.",
    question: "최소 베팅(민벳) 금액은?",
    options: ["$1 (칩 1개)", "BB와 동일한 금액", "$25 (팟의 절반)", "아무 금액이나 가능"],
    correctIndex: 1,
    explanation: "포스트플롭에서 첫 베팅의 최소 금액은 빅 블라인드(BB)와 같습니다. 1/2 게임이면 민벳 = $2. 오프닝 베팅(첫 베팅)의 최소 금액은 BB와 같다는 규칙을 기억하세요. 실전에서 민벳은 약한 핸드로 저렴하게 팟을 가져가려는 시도로 사용되기도 합니다.",
    hint: "포스트플롭 첫 베팅(오프닝 베팅)의 민벳 = BB 금액",
    potSize: "$50",
  },
  {
    id: "mr-8",
    difficulty: "diamond",
    scenario: "1/2 게임. 프리플롭에서 상대방이 $7로 레이즈합니다. 당신이 할 수 있는 액션은?",
    question: "이 상황에서 가능한 합법적 액션은?",
    options: [
      "폴드, 콜($7), 또는 민레이즈($12) 이상으로 레이즈",
      "폴드, 콜($7), 또는 $8로 레이즈",
      "폴드 또는 콜만 가능",
      "폴드, 콜, 체크, 또는 레이즈"
    ],
    correctIndex: 0,
    explanation: "상대 레이즈 $7 (인상분 $7-$2=$5). 민레이즈 = $7(콜)+$5(인상분) = $12. 옵션: 폴드, $7 콜, 또는 $12 이상 레이즈. $12 미만으로는 레이즈할 수 없고, 베팅이 있으므로 체크도 불가합니다. 실전에서 가능한 액션을 즉시 파악하는 것이 원활한 게임 진행의 기본입니다.",
    hint: "베팅이 있으면 체크 불가. 레이즈는 민레이즈 이상이어야 합니다.",
    betSize: "$7",
  },
  {
    id: "mr-7",
    difficulty: "heart",
    scenario: "토너먼트. 블라인드 500/1000. UTG가 2000 레이즈. CO가 5000으로 3-벳. BTN이 올인 7500칩(남은 전부).",
    question: "BTN의 올인이 '풀 레이즈'가 아닌 '숏 올인'일 때 다른 플레이어의 옵션은?",
    options: [
      "인상분(2500)이 최소 인상분(3000)보다 적으므로 이미 행동한 모든 플레이어는 리레이즈 불가, 콜/폴드만 가능",
      "올인은 금액과 관계없이 풀 레이즈로 간주된다",
      "누구든 리레이즈 가능",
      "올인 금액과 관계없이 모두 폴드해야 한다"
    ],
    correctIndex: 0,
    explanation: "BTN의 올인 7500은 '숏 올인'입니다. 이유: CO의 3-벳 인상분 = 5000-2000 = 3000, BTN의 인상분 = 7500-5000 = 2500. 2500 < 3000이므로 풀 레이즈 요건을 충족하지 못합니다. 숏 올인은 베팅을 재개(reopen)하지 않으므로, 이미 행동한 UTG와 CO는 콜 또는 폴드만 가능합니다. 토너먼트에서 숏스택의 올인이 풀 레이즈인지 판단하는 것은 중요한 규칙 지식입니다.",
    hint: "숏 올인(인상분 < 최소 인상분)이면 이미 레이즈한 플레이어는 리레이즈 불가.",
    potSize: "$8,500",
    betSize: "$7,500",
  },
  {
    id: "mr-9",
    difficulty: "heart",
    scenario: "라이브 게임. $5 베팅에 한 플레이어가 아무 선언 없이 $25칩 1개를 넣습니다.",
    question: "'원 칩 룰'에 의해 이 액션은 어떻게 처리됩니까?",
    options: [
      "콜($5)로 간주, 나머지 $20은 거스름돈",
      "$25 레이즈로 간주",
      "딜러가 의도를 물어봄",
      "폴드로 간주"
    ],
    correctIndex: 0,
    explanation: "원 칩 룰: 선언(레이즈) 없이 칩 하나만 넣으면 금액에 관계없이 콜로 간주됩니다. $5 베팅에 $25칩 하나를 넣으면 콜($5)이고 나머지 $20은 거스름돈입니다. 레이즈하려면 '레이즈'를 먼저 선언한 후 칩을 넣어야 합니다. 라이브 게임에서 이 규칙을 모르면 의도와 다른 액션이 될 수 있으므로 반드시 기억하세요.",
    hint: "선언 없이 칩 1개만 넣으면 콜로 간주됩니다 (원 칩 룰).",
  },
  {
    id: "mr-10",
    difficulty: "spade",
    scenario: "리버. 팟 $200. 당신이 $60 베팅. 상대가 '레이즈 투 $180'을 선언합니다.",
    question: "이 레이즈는 합법적입니까?",
    options: [
      "예 — 인상분 $120 > 민레이즈 인상분 $60",
      "아니오 — 민레이즈는 $120이어야 한다",
      "예 — 팟 사이즈 이하이므로 가능",
      "아니오 — 리버에서는 레이즈 불가"
    ],
    correctIndex: 0,
    explanation: "당신 베팅 $60. 민레이즈 인상분 = $60. 최소 레이즈 = $60+$60 = $120. 상대 레이즈 $180 → 인상분 = $180-$60 = $120 ≥ $60(민인상분)이므로 합법적인 레이즈입니다. 실전에서 상대의 레이즈가 합법적인지 판단하려면 인상분이 이전 베팅/레이즈 이상인지 확인하면 됩니다.",
    hint: "인상분이 이전 베팅/레이즈 금액 이상이면 합법 레이즈입니다.",
    potSize: "$200",
    betSize: "$60",
  },
  {
    id: "mr-12",
    difficulty: "spade",
    scenario: "플롭에서 3명이 참여. 팟 $30. 플레이어A $15 베팅, 플레이어B $50 레이즈, 당신 차례.",
    question: "민레이즈 금액은?",
    options: ["$85", "$100", "$65", "$50"],
    correctIndex: 0,
    explanation: "B의 인상분 = $50 - $15 = $35. 민레이즈 = $50(콜) + $35(인상분) = $85. 레이즈 체인에서 각 레이즈의 인상분은 최소한 이전 레이즈의 인상분만큼이어야 합니다. 멀티웨이에서 레이즈 전쟁이 벌어질 때 이 계산을 빠르게 할 수 있으면 게임 흐름을 놓치지 않습니다.",
    hint: "인상분 = 이전 레이즈 - 그 전 베팅. 민레이즈 = 콜 + 인상분.",
    potSize: "$30",
    betSize: "$50",
  },
  {
    id: "mr-13",
    difficulty: "spade",
    scenario: "2/5 게임. 프리플롭. A가 $15 오픈 레이즈, B가 $40으로 3-벳, A가 $40 콜. 이후 C가 스택 $55 전부로 올인합니다. C의 추가 금액은 $15($55-$40)로, B의 인상분 $25($40-$15)에 미달합니다.",
    question: "C의 숏 올인($55) 후, 이미 액션을 완료한 A와 B는 리레이즈할 수 있습니까?",
    options: [
      "아니오 — C의 올인이 풀 레이즈 미만(인상분 $15 < 최소 $25)이므로 이미 액션을 완료한 A, B는 콜/폴드만 가능",
      "예 — 올인은 항상 베팅을 리오픈한다",
      "예 — 금액이 올랐으므로 누구나 레이즈 가능",
      "아니오 — 올인 후에는 모든 베팅이 종료된다"
    ],
    correctIndex: 0,
    explanation: "C의 올인 $55는 '숏 올인'입니다. B의 3-벳 인상분 = $40-$15 = $25. C의 인상분 = $55-$40 = $15. $15 < $25이므로 풀 레이즈 요건에 미달합니다. 숏 올인은 베팅을 리오픈(reopen)하지 않으므로, 이미 3-벳에 대해 액션을 완료한 A(콜)와 B(3-벳)는 콜/폴드만 가능합니다. 만약 C의 올인이 $65 이상이었다면(인상분 $25 이상) 풀 레이즈로 간주되어 A와 B에게 다시 레이즈 기회가 열렸을 것입니다. 이 규칙은 토너먼트에서 숏스택 올인 시 자주 적용됩니다.",
    hint: "올인 금액이 풀 레이즈(이전 인상분 이상)에 미달하면 이미 액션한 플레이어에게 베팅이 리오픈되지 않습니다.",
    betSize: "$55",
  },
];
